CREATE TABLE IF NOT EXISTS "user"
(
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS item
(
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_available BOOLEAN      NOT NULL,
    owner_id    INTEGER,
    request     INTEGER,
    FOREIGN KEY (owner_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start     TIMESTAMP   NOT NULL,
    "end"  TIMESTAMP   NOT NULL,
    item_id   INTEGER     NOT NULL,
    booker_id INTEGER     NOT NULL,
    status    VARCHAR(50)   NOT NULL,
    FOREIGN KEY (item_id) REFERENCES item (id),
    FOREIGN KEY (booker_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS item_request
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(1000) NOT NULL,
    requester_id INTEGER       NOT NULL,
    created      TIMESTAMP     NOT NULL,
    FOREIGN KEY (requester_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS comment
(
    id           INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id    INTEGER  NOT NULL,
    item_id      INTEGER  NOT NULL,
    text  VARCHAR(2000) NOT NULL,
    created      TIMESTAMP     NOT NULL,
    FOREIGN KEY (author_id) REFERENCES "user" (id),
    FOREIGN KEY (item_id) REFERENCES Item (id)
)
